import type { InterviewTimelineRecord } from '../types'

export const defaultInterviewTimeline: InterviewTimelineRecord[] = [
 {
 id: 'int-1',
 jobId: 1,
 company: 'Google',
 jobTitle: 'Senior Product Manager',
 roundType: '技术面',
 roundNumber: 2,
 status: '已安排',
 scheduledAt: new Date(Date.now() + 86400000).toISOString(),
 durationMinutes: 60,
 location: '',
 meetingUrl: 'https://meet.example.com/abc',
 interviewer: '张工 · Staff PM',
 remark: '准备产品案例',
 },
 {
 id: 'int-2',
 jobId: 2,
 company: 'Microsoft',
 jobTitle: 'Product Manager',
 roundType: 'HR初筛',
 roundNumber: 1,
 status: '已完成',
 scheduledAt: new Date(Date.now() - 172800000).toISOString(),
 durationMinutes: 30,
 interviewer: 'Lisa',
 debrief: {
 questions: ['介绍一个你主导的项目', '如何与研发协作排期'],
 selfRating: 4,
 highlights: ['STAR 结构清晰', '数据指标准备充分'],
 improvements: ['英文术语可更流利'],
 followUp: '等待二面通知',
 otherNotes: '整体氛围友好',
 },
 },
 {
 id: 'int-3',
 jobId: 3,
 company: 'Meta',
 jobTitle: 'Product Lead',
 roundType: '总监面',
 roundNumber: 3,
 status: '已改期',
 scheduledAt: new Date(Date.now() + 259200000).toISOString(),
 durationMinutes: 45,
 remark: '由原周三改至周五',
 },
]
